version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_RESULT_BACKEND=redis://redis:6379/1
    env_file:
      - .env
    volumes:
      - ./assets:/app/assets
      - ./outputs:/app/outputs
    depends_on:
      - redis
    command: uvicorn api.main:app --host 0.0.0.0 --port 5000 --reload

  worker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_RESULT_BACKEND=redis://redis:6379/1
    env_file:
      - .env
    volumes:
      - ./assets:/app/assets
      - ./outputs:/app/outputs
    depends_on:
      - redis
    command: celery -A workers.tasks worker --loglevel=INFO --concurrency=2

volumes:
  redis_data:
